
import React, { useState, useEffect } from 'react';
import { 
  Github, 
  Terminal, 
  Code2, 
  ArrowRight, 
  Loader2, 
  CheckCircle2, 
  FileJson, 
  FileCode, 
  AlertCircle,
  Play,
  Sparkles,
  LogOut
} from 'lucide-react';
import { AppStep, GeneratedFile, RepoInfo, BuildShipContext } from './types';
import { GitHubService } from './services/githubService';
import { GeminiService } from './services/geminiService';
import { MOCK_PACKAGE_JSON, MOCK_FLOW_MAPPING } from './constants';

const geminiService = new GeminiService();

export default function App() {
  // Initialize from localStorage if available
  const [step, setStep] = useState<AppStep>(AppStep.SETUP);
  const [repoUrl, setRepoUrl] = useState(() => localStorage.getItem('bs_repo_url') || '');
  const [ghToken, setGhToken] = useState(() => localStorage.getItem('bs_gh_token') || '');
  
  const [userPrompt, setUserPrompt] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isRefining, setIsRefining] = useState(false);
  
  const [repoInfo, setRepoInfo] = useState<RepoInfo | null>(null);
  const [generatedFiles, setGeneratedFiles] = useState<GeneratedFile[]>([]);
  const [selectedFileIndex, setSelectedFileIndex] = useState<number>(0);
  const [prResult, setPrResult] = useState<{ url: string, number: number } | null>(null);
  const [aiSummary, setAiSummary] = useState('');

  // 1. Connect to GitHub
  const handleConnect = async () => {
    setError(null);
    const info = GitHubService.parseRepoUrl(repoUrl);
    
    if (!info) {
      setError('Invalid GitHub URL. Format: https://github.com/owner/repo');
      return;
    }
    
    setIsLoading(true);
    const ghService = new GitHubService(ghToken);
    const hasAccess = await ghService.checkRepoAccess(info);

    if (hasAccess) {
      // Save credentials on success
      localStorage.setItem('bs_repo_url', repoUrl);
      localStorage.setItem('bs_gh_token', ghToken);
      
      setRepoInfo(info);
      setStep(AppStep.DASHBOARD);
    } else {
      setError('Cannot access repository. Please check URL and Token permissions (Repo scope required).');
    }
    setIsLoading(false);
  };

  const handleDisconnect = () => {
    localStorage.removeItem('bs_repo_url');
    localStorage.removeItem('bs_gh_token');
    setRepoUrl('');
    setGhToken('');
    setRepoInfo(null);
    setStep(AppStep.SETUP);
  };

  // 2. Refine Prompt
  const handleRefine = async () => {
    if (!userPrompt.trim()) return;
    setIsRefining(true);
    setError(null);
    try {
      const refined = await geminiService.refinePrompt(userPrompt);
      setUserPrompt(refined);
    } catch (e: any) {
      setError('Failed to enhance prompt. Please try again.');
    } finally {
      setIsRefining(false);
    }
  };

  // 3. Generate Code
  const handleGenerate = async () => {
    if (!repoInfo || !userPrompt) return;
    setIsLoading(true);
    setStep(AppStep.GENERATING);
    setError(null);

    try {
      const ghService = new GitHubService(ghToken);
      // Attempt to fetch real context, fallback to mocks
      let pkgJson = MOCK_PACKAGE_JSON;
      let flowMap = MOCK_FLOW_MAPPING;
      let existingNodes: string[] = [];
      
      try {
        const fetchedPkg = await ghService.getFileContent(repoInfo, 'package.json');
        if (fetchedPkg) pkgJson = fetchedPkg;
        const fetchedMap = await ghService.getFileContent(repoInfo, 'flow-id-to-label.json');
        if (fetchedMap) flowMap = fetchedMap;
        
        // Fetch existing node structure to infer naming
        existingNodes = await ghService.getExistingNodes(repoInfo);
      } catch (err) {
        console.warn('Could not fetch context files, using defaults', err);
      }

      const context: BuildShipContext = {
        packageJson: pkgJson,
        flowIdMapping: flowMap,
        existingNodes
      };

      const result = await geminiService.generateBuildShipFiles({
        repoInfo,
        userPrompt,
        context
      });

      setGeneratedFiles(result.files);
      setSelectedFileIndex(0);
      setAiSummary(result.summary);
      setStep(AppStep.REVIEW);

    } catch (e: any) {
      setError(e.message || 'Generation failed');
      setStep(AppStep.DASHBOARD);
    } finally {
      setIsLoading(false);
    }
  };

  // 4. Create PR
  const handleCreatePR = async () => {
    if (!repoInfo || generatedFiles.length === 0) return;
    setIsLoading(true);
    setStep(AppStep.SUBMITTING);
    setError(null);

    try {
      const ghService = new GitHubService(ghToken);
      const result = await ghService.createPullRequest(
        repoInfo,
        generatedFiles,
        `BuildShip AI: ${aiSummary.slice(0, 50)}...`,
        `## Automated BuildShip Update\n\n${aiSummary}\n\nGenerated by BuildShip AI Architect.`
      );
      setPrResult(result);
      setStep(AppStep.SUCCESS);
    } catch (e: any) {
      setError(e.message || 'Failed to create Pull Request');
      setStep(AppStep.REVIEW);
    } finally {
      setIsLoading(false);
    }
  };

  // --- RENDER HELPERS ---

  const renderFileIcon = (path: string) => {
    if (path.endsWith('.json')) return <FileJson className="w-4 h-4 text-yellow-400" />;
    if (path.endsWith('.ts')) return <FileCode className="w-4 h-4 text-blue-400" />;
    return <Code2 className="w-4 h-4 text-gray-400" />;
  };

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex flex-col font-sans">
      {/* Header */}
      <header className="border-b border-slate-800 bg-slate-900/50 backdrop-blur-md sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-600 to-brand-800 flex items-center justify-center shadow-lg shadow-brand-900/50">
              <Terminal className="w-5 h-5 text-white" />
            </div>
            <h1 className="font-bold text-xl tracking-tight">BuildShip <span className="text-brand-400">AI Architect</span></h1>
          </div>
          {repoInfo && (
            <div className="flex items-center gap-4">
              <div className="text-sm text-slate-400 flex items-center gap-2 bg-slate-800 px-3 py-1 rounded-full border border-slate-700">
                <Github className="w-4 h-4" />
                <span>{repoInfo.owner}/{repoInfo.name}</span>
              </div>
              <button 
                onClick={handleDisconnect}
                className="p-2 text-slate-400 hover:text-red-400 hover:bg-slate-800 rounded-full transition-colors"
                title="Disconnect & Clear Credentials"
              >
                <LogOut className="w-4 h-4" />
              </button>
            </div>
          )}
        </div>
      </header>

      <main className="flex-1 max-w-5xl mx-auto w-full p-6">
        
        {/* Error Display */}
        {error && (
          <div className="mb-6 p-4 bg-red-900/20 border border-red-500/50 rounded-lg flex items-center gap-3 text-red-200 animate-in slide-in-from-top-2">
            <AlertCircle className="w-5 h-5 flex-shrink-0" />
            <p>{error}</p>
          </div>
        )}

        {/* STEP 1: SETUP */}
        {step === AppStep.SETUP && (
          <div className="max-w-md mx-auto mt-12 bg-slate-800/50 p-8 rounded-2xl border border-slate-700 shadow-xl">
            <h2 className="text-2xl font-bold mb-2">Connect Repository</h2>
            <p className="text-slate-400 mb-6">Enter your BuildShip repository details to begin.</p>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">GitHub Repository URL</label>
                <input 
                  type="text" 
                  placeholder="https://github.com/user/buildship" 
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 focus:ring-2 focus:ring-brand-500 focus:outline-none transition-all placeholder-slate-600"
                  value={repoUrl}
                  onChange={e => setRepoUrl(e.target.value)}
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">GitHub Personal Access Token</label>
                <input 
                  type="password" 
                  placeholder="ghp_..." 
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 focus:ring-2 focus:ring-brand-500 focus:outline-none transition-all placeholder-slate-600"
                  value={ghToken}
                  onChange={e => setGhToken(e.target.value)}
                />
                <p className="text-xs text-slate-500 mt-2 flex justify-between">
                  <span>Token requires <code>repo</code> scope.</span>
                  {localStorage.getItem('bs_gh_token') && <span className="text-green-400">Credentials saved</span>}
                </p>
              </div>

              <button 
                onClick={handleConnect}
                disabled={isLoading || !repoUrl || !ghToken}
                className="w-full bg-brand-600 hover:bg-brand-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-3 rounded-lg transition-all flex items-center justify-center gap-2 mt-2"
              >
                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <>Connect <ArrowRight className="w-5 h-5" /></>}
              </button>
            </div>
          </div>
        )}

        {/* STEP 2: DASHBOARD */}
        {step === AppStep.DASHBOARD && (
          <div className="mt-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="text-center mb-10">
              <h2 className="text-3xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">What would you like to build?</h2>
              <p className="text-slate-400 max-w-lg mx-auto">
                Describe a new node logic, a modification to an existing node, or a new workflow structure. The AI will generate compliant files.
              </p>
            </div>

            <div className="max-w-3xl mx-auto relative">
              <div className="absolute -inset-1 bg-gradient-to-r from-brand-600 to-purple-600 rounded-2xl blur opacity-25"></div>
              <div className="relative bg-slate-800 rounded-xl p-2 shadow-2xl">
                <textarea 
                  className="w-full bg-transparent text-lg text-slate-200 p-4 min-h-[160px] focus:outline-none resize-none placeholder-slate-600"
                  placeholder="e.g., Create a node that takes a PDF URL input, extracts text using a library, and returns the string. Ensure it handles timeout errors."
                  value={userPrompt}
                  onChange={e => setUserPrompt(e.target.value)}
                />
                <div className="flex justify-between items-center p-2 border-t border-slate-700/50 bg-slate-800/50 rounded-b-xl">
                  <button
                    onClick={handleRefine}
                    disabled={!userPrompt.trim() || isRefining}
                    className="text-brand-300 hover:text-white hover:bg-white/10 px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 disabled:opacity-50"
                  >
                    {isRefining ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                    Enhance Prompt
                  </button>

                  <button 
                    onClick={handleGenerate}
                    disabled={!userPrompt.trim()}
                    className="bg-brand-600 hover:bg-brand-500 text-white px-6 py-2 rounded-lg font-medium transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-brand-900/30"
                  >
                    Generate Plan <Play className="w-4 h-4 fill-current" />
                  </button>
                </div>
              </div>
            </div>

            {/* Quick Tips */}
            <div className="max-w-3xl mx-auto mt-12 grid grid-cols-1 md:grid-cols-3 gap-6">
              {[
                { title: "Custom Nodes", desc: "Logic blocks with Typescript" },
                { title: "Workflows", desc: "Orchestrate nodes via JSON" },
                { title: "Safe Updates", desc: "Preserves existing IO keys" }
              ].map((tip, i) => (
                <div key={i} className="bg-slate-800/30 border border-slate-800 p-5 rounded-xl">
                  <h3 className="font-semibold text-brand-300 mb-1">{tip.title}</h3>
                  <p className="text-sm text-slate-500">{tip.desc}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* STEP 3: GENERATING (Loading) */}
        {step === AppStep.GENERATING && (
          <div className="flex flex-col items-center justify-center h-[60vh] animate-in fade-in duration-700">
            <div className="relative w-24 h-24 mb-8">
              <div className="absolute inset-0 border-4 border-slate-700 rounded-full"></div>
              <div className="absolute inset-0 border-4 border-brand-500 rounded-full border-t-transparent animate-spin"></div>
              <Code2 className="absolute inset-0 m-auto w-8 h-8 text-brand-400" />
            </div>
            <h3 className="text-2xl font-bold text-white mb-2">Architecting Solution...</h3>
            <p className="text-slate-400">Analyzing strict requirements and generating files.</p>
          </div>
        )}

        {/* STEP 4: REVIEW */}
        {step === AppStep.REVIEW && (
          <div className="animate-in fade-in slide-in-from-bottom-8 duration-500">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <span className="w-8 h-8 rounded-full bg-green-500/20 text-green-400 flex items-center justify-center text-sm border border-green-500/30">✓</span>
                Review Generated Changes
              </h2>
              <div className="flex gap-3">
                <button 
                  onClick={() => setStep(AppStep.DASHBOARD)}
                  className="px-4 py-2 text-slate-400 hover:text-white transition-colors"
                >
                  Discard
                </button>
                <button 
                  onClick={handleCreatePR}
                  className="bg-brand-600 hover:bg-brand-500 text-white px-6 py-2 rounded-lg font-bold shadow-lg shadow-brand-900/50 flex items-center gap-2 transition-all"
                >
                  <Github className="w-4 h-4" />
                  Create Pull Request
                </button>
              </div>
            </div>

            <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden shadow-2xl">
              <div className="grid grid-cols-[250px_1fr] h-[600px]">
                {/* File Tree */}
                <div className="border-r border-slate-700 bg-slate-900/50 p-4 overflow-y-auto">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4">Modified Files</h3>
                  <div className="space-y-1">
                    {generatedFiles.map((file, idx) => (
                      <button
                        key={idx}
                        onClick={() => setSelectedFileIndex(idx)}
                        className={`w-full group flex items-center gap-2 text-sm p-2 rounded cursor-pointer transition-colors text-left ${
                          selectedFileIndex === idx 
                            ? 'bg-brand-600/20 text-white ring-1 ring-brand-500/50' 
                            : 'text-slate-300 hover:text-white hover:bg-slate-700/50'
                        }`}
                      >
                        {renderFileIcon(file.path)}
                        <span className="truncate" title={file.path}>
                          {file.path.split('/').pop()}
                        </span>
                        <span className="text-xs text-slate-600 ml-auto opacity-0 group-hover:opacity-100">{file.type}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* File Preview */}
                <div className="bg-slate-900 overflow-y-auto p-0">
                  {generatedFiles.length > 0 && generatedFiles[selectedFileIndex] && (
                    <div className="flex flex-col h-full">
                       <div className="bg-slate-800/80 px-4 py-2 border-b border-slate-700 text-xs font-mono text-slate-400 sticky top-0">
                          {generatedFiles[selectedFileIndex].path}
                       </div>
                       <pre className="p-4 text-sm font-mono text-slate-300 leading-relaxed whitespace-pre-wrap">
                        <code>{generatedFiles[selectedFileIndex].content}</code>
                       </pre>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* STEP 5: SUBMITTING */}
        {step === AppStep.SUBMITTING && (
          <div className="flex flex-col items-center justify-center h-[60vh] animate-in fade-in">
             <div className="relative w-20 h-20 mb-8">
              <div className="absolute inset-0 border-4 border-brand-500 rounded-full border-b-transparent animate-spin"></div>
            </div>
            <h3 className="text-2xl font-bold text-white mb-2">Pushing to GitHub</h3>
            <p className="text-slate-400">Creating branch, committing files, and opening PR...</p>
          </div>
        )}

        {/* STEP 6: SUCCESS */}
        {step === AppStep.SUCCESS && prResult && (
          <div className="max-w-xl mx-auto mt-20 text-center animate-in zoom-in-95 duration-500">
            <div className="w-24 h-24 bg-green-500/20 rounded-full flex items-center justify-center mx-auto mb-6 border border-green-500/30">
              <CheckCircle2 className="w-12 h-12 text-green-400" />
            </div>
            <h2 className="text-3xl font-bold text-white mb-4">Pull Request Created!</h2>
            <p className="text-slate-400 mb-8">
              Your changes have been successfully architected and pushed to the repository. 
              Review the PR details on GitHub to merge.
            </p>
            
            <a 
              href={prResult.url} 
              target="_blank" 
              rel="noreferrer"
              className="inline-flex items-center gap-2 bg-slate-100 text-slate-900 hover:bg-white px-8 py-4 rounded-xl font-bold transition-all transform hover:scale-105"
            >
              <Github className="w-5 h-5" />
              View PR #{prResult.number}
            </a>

            <button 
              onClick={() => { setStep(AppStep.DASHBOARD); setUserPrompt(''); setGeneratedFiles([]); }}
              className="block mx-auto mt-8 text-slate-500 hover:text-slate-300 transition-colors"
            >
              Create another workflow
            </button>
          </div>
        )}

      </main>
    </div>
  );
}
